apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-operator
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: CORE_DOCKER_IMAGE
            value: quay.io/goharbor/harbor-core:v2.1.2
          - name: JOBSERVICE_DOCKER_IMAGE
            value: quay.io/goharbor/harbor-jobservice:v2.1.2
          - name: PORTAL_DOCKER_IMAGE
            value: quay.io/goharbor/harbor-portal:v2.1.2
          - name: REGISTRYCTL_DOCKER_IMAGE
            value: quay.io/goharbor/harbor-registryctl:v2.1.2
          - name: REGISTRY_DOCKER_IMAGE
            value: quay.io/goharbor/registry-photon:v2.1.2