apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Override namespace
namespace: harbor-operator-ns

# Common annotations
commonAnnotations:
  goharbor.io/operator-version: "v1.0.0"
  goharbor.io/deploy-mode: "harbor"
  goharbor.io/deploy-engine: "Kustomization"

# All the referred deployment manifests
resources:
  - namespace.yaml
  - ../../config/default # harbor operator

images:
  - name: goharbor/harbor-operator
    newName: goharbor/harbor-operator
    newTag: latest